# Generated by Django 4.0.6 on 2022-07-14 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='производитель')),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производитель',
            },
        ),
        migrations.CreateModel(
            name='TransportTypeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='тип')),
            ],
            options={
                'verbose_name': 'тип транспорта',
                'verbose_name_plural': 'тип транспорта',
            },
        ),
        migrations.CreateModel(
            name='TransportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_model', models.CharField(blank=True, max_length=30, verbose_name='модель')),
                ('year', models.CharField(blank=True, max_length=30, verbose_name='год производства')),
                ('age_limit', models.PositiveIntegerField(blank=True, verbose_name='возрастное ограничение')),
                ('information', models.TextField(blank=True, max_length=500, verbose_name='информация')),
                ('rental_price', models.PositiveIntegerField(blank=True, verbose_name='стоимость аренды')),
                ('deposit', models.PositiveIntegerField(blank=True, verbose_name='сумма залога')),
                ('image', models.ImageField(blank=True, upload_to='static/imgTransport', verbose_name='изображение')),
                ('manufacturer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transportapp.manufacturermodel', verbose_name='производитель')),
                ('transport_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец')),
                ('transport_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='transportapp.transporttypemodel', verbose_name='тип')),
            ],
            options={
                'verbose_name': 'транспорт',
                'verbose_name_plural': 'транспорт',
            },
        ),
    ]
