# Generated by Django 4.0.6 on 2022-07-17 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0002_alter_transportmodel_age_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='imgTransport/', verbose_name='изображение'),
        ),
    ]
