# Generated by Django 4.0.6 on 2022-07-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0003_alter_transportmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportmodel',
            name='deposit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='сумма залога'),
        ),
    ]
